#!/usr/bin/expect -f


#set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
#if {$force_conservative} {
#	set send_slow {1 .1}
#	proc send {ignore arg} {
#		sleep .1
#		exp_send -s -- $arg
#	}
#}

set timeout -1
spawn sudo passenger-install-apache2-module
expect "Press Enter to continue, or Ctrl-C to abort."
send -- "\r"

expect "Press ENTER to continue."
send -- "\r"
expect eof
